name:  CI Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlite3  
    - name: Run tests
      run: |
        chmod +x ./project/tests.sh
        ./project/tests.sh
